### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by egeergul** [Expert-Developer-Finder/ExDevWeb#8]
- [x] Update bio çalışacak repos
- [x]  Delete account çalışacak
- [x] create repo da github rest api kontrol edilecek
- [x]  Repo ların view i gözükecek
- [x] add pp eklenecek
- [x]  join repo için hem credential check hem de request ile yapmka gerek
- [x] home da repo owner ı olduğun ve olmadığın repolar gözükecek
- [x] Join repository kalan logic bitecek
- [x] repository lere password attribute u ve onu değiştirmek gelecek
- [ ] authentication içi error mesajları logic i bi temize çekilecek frontda
- [ ] middleware eklenecek
- [ ] loading vs eklenecek
- [ ] getJoinedMembers'ı daha efficient şekilde yazmaya çalış
- [ ] delete repo
- [ ] pending olan developer aynı anda shared secretla ikinciye girmeye çalışırsa pending düşmeli
- [x] Eray hocaya sroru: gerçek müşterilere kullandırtcaz ama private repo nun her şeyini çekerkene biz bunun sorumluluunu almasaks mı
- [x] github authentication lazım yani enin omayan repo lar ekleyememem lazm
- [x] about us a eray hocayı ekle
- [x] batman butonunu değiştir
- [ ] demote da kendini dmeote edeibliyon ve repo, ownersiz kalabiliyor
